<a href="https://colab.research.google.com/github/cluePrints/fastai-v3-notes/blob/master/fast_ai3_lesson_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
!pip install fastai pandas sklearn numpy pillow torch -q

spacy 2.0.18 has requirement numpy>=1.15.0, but you'll have numpy 1.14.6 which is incompatible.


In [0]:
from torch import tensor
from torch import nn
import torch
import matplotlib.pyplot as plt
import numpy as np

In [4]:
n = 100
x = torch.ones(n)
x.uniform_(0, 1)
x[:5]

tensor([0.5067, 0.7484, 0.5183, 0.0127, 0.8115])

In [0]:
orig_params = tensor([3.,1])

In [6]:
# Note to self: 2nd column was needed to vectorize ax+b: a*x+b*1 = [a,b] . [x, 1]
x__matrix = torch.cat([x.unsqueeze(1), torch.ones(n).unsqueeze(1)], dim=1)
x__matrix[:5]

tensor([[0.5067, 1.0000],
        [0.7484, 1.0000],
        [0.5183, 1.0000],
        [0.0127, 1.0000],
        [0.8115, 1.0000]])

In [0]:
y = x__matrix@orig_params + torch.rand(n)

In [8]:
y[:5]

tensor([3.1091, 4.1390, 3.2433, 1.7744, 3.6597])

In [0]:
p = nn.Parameter(tensor([1.,0]))

In [0]:
def mse_loss(y, y_hat):
  return ((y-y_hat)**2).mean()

In [11]:
(x__matrix@p)[:5], y[:5]

(tensor([0.5067, 0.7484, 0.5183, 0.0127, 0.8115], grad_fn=<SliceBackward>),
 tensor([3.1091, 4.1390, 3.2433, 1.7744, 3.6597]))

In [12]:
mse_loss(y, x__matrix@p)

tensor(6.6486, grad_fn=<MeanBackward1>)

In [0]:
 # Note to self: otherwise animation.to_jshtml() needed
from matplotlib import rc
rc('animation', html='jshtml')

In [0]:
lr = 0.1
def update(params, print_loss=False):
  y_hat = x__matrix@params
  loss = mse_loss(y, y_hat)
  if print_loss: print("Loss: " + str(loss))
  loss.backward()
  with torch.no_grad():
    p.sub_(p.grad * lr)
    # zeroing grad is to prevent accumulation, otherwise it will grow we won't converge
    p.grad.zero_()

In [17]:
a = tensor([1.,0])
p = nn.Parameter(a)

from matplotlib.animation import FuncAnimation
fig = plt.figure()
line, = plt.plot(x.numpy(), (x__matrix@a).numpy())
plt.scatter(x, y, c='orange')
plt.close()

def animate(i):
  line.set_ydata(x__matrix@a)
  print_loss = (i % 10 == 0)
  update(p, print_loss)
 
FuncAnimation(fig, func=animate, frames=np.arange(0,100), interval=20)

Loss: tensor(6.6486, grad_fn=<MeanBackward1>)
Loss: tensor(3.7877, grad_fn=<MeanBackward1>)
Loss: tensor(0.1509, grad_fn=<MeanBackward1>)
Loss: tensor(0.1244, grad_fn=<MeanBackward1>)
Loss: tensor(0.1125, grad_fn=<MeanBackward1>)
Loss: tensor(0.1036, grad_fn=<MeanBackward1>)
Loss: tensor(0.0969, grad_fn=<MeanBackward1>)
Loss: tensor(0.0919, grad_fn=<MeanBackward1>)
Loss: tensor(0.0881, grad_fn=<MeanBackward1>)
Loss: tensor(0.0852, grad_fn=<MeanBackward1>)
Loss: tensor(0.0830, grad_fn=<MeanBackward1>)
